# Import required libraries for data analysis and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Path where all dataset files are stored
path = r"C:\Users\isha1\OneDrive\Pictures\Documents\GitHub\raw"

# Load all datasets
customers = pd.read_csv(path + "\\Customers.csv", encoding='latin1')
products = pd.read_csv(path + "\\Products.csv", encoding='latin1')
sales = pd.read_csv(path + "\\Sales.csv", encoding='latin1')
stores = pd.read_csv(path + "\\Stores.csv", encoding='latin1')
exchange = pd.read_csv(path + "\\Exchange_Rates.csv", encoding='latin1')

# Preview first few rows to understand the structure of each dataset
print(customers.head())
print(products.head())
print(sales.head())

# Check number of rows and columns in each dataset
print(customers.shape)
print(products.shape)
print(sales.shape)

# Get basic information about columns, data types, and null values
print(customers.info())
print(products.info())
print(sales.info())

# Convert order and delivery dates into datetime format for time analysis
sales['Order Date'] = pd.to_datetime(sales['Order Date'])
sales['Delivery Date'] = pd.to_datetime(sales['Delivery Date'])

# Check if there are any missing values in the sales dataset
print(sales.isnull().sum())

# Merge all datasets to create a single dataframe for analysis
df = sales.merge(products, on="ProductKey") \
          .merge(customers, on="CustomerKey") \
          .merge(stores, on="StoreKey")

# Preview merged dataset
print(df.head())

# Remove currency symbols from Unit Price column and convert to numeric
df['Unit Price USD'] = df['Unit Price USD'].replace('[\$,]', '', regex=True).astype(float)

# Create a new column for total revenue
df['Revenue'] = df['Quantity'] * df['Unit Price USD']

# Calculate total revenue generated
total_revenue = df['Revenue'].sum()
print("Total Revenue:", total_revenue)

# Identify top 10 products based on revenue
top_products = df.groupby("Product Name")['Revenue'].sum().sort_values(ascending=False).head(10)

print(top_products)

# Visualize top selling products
top_products.plot(kind="bar")
plt.title("Top Selling Products")
plt.ylabel("Revenue")
plt.show()

# Calculate revenue generated from each country
country_sales = df.groupby("Country_x")['Revenue'].sum().sort_values(ascending=False)

print(country_sales)

# Plot top 10 countries by revenue
country_sales.head(10).plot(kind="bar")
plt.title("Revenue by Country")
plt.show()

# Extract year from order date for yearly sales trend
df['Year'] = df['Order Date'].dt.year

# Calculate total revenue per year
yearly_sales = df.groupby('Year')['Revenue'].sum()

print(yearly_sales)

# Plot yearly sales trend
yearly_sales.plot(marker='o')
plt.title("Yearly Sales Trend")
plt.ylabel("Revenue")
plt.show()

# Calculate delivery time in days
df['Delivery_Days'] = (df['Delivery Date'] - df['Order Date']).dt.days

# Calculate average delivery time
avg_delivery = df['Delivery_Days'].mean()

print("Average Delivery Time:", avg_delivery)

# Revenue generated by each store
channel_sales = df.groupby("StoreKey")['Revenue'].sum()

print(channel_sales)

# Check gender distribution of customers
gender_distribution = customers['Gender'].value_counts()

print(gender_distribution)

# Visualize gender distribution using pie chart
gender_distribution.plot(kind="pie", autopct="%1.1f%%")
plt.title("Customer Gender Distribution")
plt.show()

# Find top 10 customers contributing the most revenue
top_customers = df.groupby("CustomerKey")['Revenue'].sum().sort_values(ascending=False).head(10)

print(top_customers)

# Visualize top customers
top_customers.plot(kind="bar")
plt.title("Top 10 Customers by Revenue")
plt.ylabel("Revenue")
plt.show()

# Extract month from order date for monthly sales analysis
df['Month'] = df['Order Date'].dt.to_period('M')

# Calculate monthly revenue
monthly_sales = df.groupby('Month')['Revenue'].sum()

# Plot monthly sales trend
monthly_sales.plot(figsize=(10,5))
plt.title("Monthly Sales Trend")
plt.ylabel("Revenue")
plt.show()

# Analyze revenue generated by each product category
category_sales = df.groupby("Category")['Revenue'].sum().sort_values(ascending=False)

print(category_sales)

# Visualize category-wise revenue
category_sales.plot(kind="bar")
plt.title("Revenue by Category")
plt.show()

# Identify top performing stores based on revenue
store_sales = df.groupby("StoreKey")['Revenue'].sum().sort_values(ascending=False).head(10)

store_sales.plot(kind="bar")
plt.title("Top Stores by Revenue")
plt.show()

# Select numerical columns for correlation analysis
numeric_df = df[['Quantity','Unit Price USD','Revenue','Delivery_Days']]

# Plot correlation heatmap to understand relationships between variables
sns.heatmap(numeric_df.corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()